#!/bin/sh
#
#   mount nfs storage
#
#   This program is free software; you can redistribute it and/or modify it under the 
#   terms of the GNU General Public License as published by the Free Software Foundation;
#   either version 3 of the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
#   without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
#   See the GNU General Public License for more details.
#  
#   You should have received a copy of the GNU General Public License along with this program; 
#   if not, see <http://www.gnu.org/licenses/>.
#
ver="1.01.01 - 15.9.2014"
retc=0
ls=""
me=`basename $0`
mounted=0

if [ -f /store/fsi/viconf.sh ] ; then
    . /store/fsi/viconf.sh
else
    echo "ERROR cannot set vi conf variables"
    exit 99
fi
if [ -f /store/fsi/fsifunc.sh ] ; then
    . /store/fsi/fsifunc.sh
else
    echo "ERROR cannot load vi functions"
    exit 99
fi

infmsg "$ls Start $me $ver"

debmsg "$ls    ==> vi temp server: $fsisrv"
debmsg "$ls    ==> vi temp mount: $fsimount"
debmsg "$ls    ==> ks mount point: $kspath"

debmsg "$ls  check if volume already mounted"

ismounted
mounted=$?

if [ $mounted -eq 0 ]; then
   infmsg "$ls  vi temp server install dir not mounted - mount now ..."
   esxcfg-nas -a nfs_fsi_$esxitree -o $fsisrv -s $fsimount
   retc=$?
   if [ $retc -ne 0 ]; then
      errmsg "cannot mount vi temp inst dir - abort"
   else
      ismounted
      retc=$?
      if [ $retc -eq 0 ]; then
         errmsg "something wrong - cannot mount vi temp inst dir - abort"
      else
         infmsg "$ls  vi temp inst mounted"
         retc=0
      fi
   fi
else
   infmsg "$ls  vi temp srv inst already mounted"
fi

infmsg "$ls End$me $ver - rc=$retc"
exit $retc
   

